CREATE DATABASE [ORDERS_DIMENSIONAL_DB]
ON PRIMARY 
( 
    NAME = 'ORDERS_DIMENSIONAL_DB', 
    FILENAME = '/Users/milenabazoyan/Desktop/ORDERS_DIMENSIONAL_DB.mdf', 
    SIZE = 10MB, 
    MAXSIZE = UNLIMITED, 
    FILEGROWTH = 10%
)
LOG ON 
( 
    NAME = 'ORDERS_DIMENSIONAL_DB_log', 
    FILENAME = '/Users/milenabazoyan/Desktop/ORDERS_DIMENSIONAL_DB.ldf', 
    SIZE = 2MB, 
    MAXSIZE = 15MB, 
    FILEGROWTH = 500KB
);
GO